name: '[DEMO] Upload Episode from YouTube To Anchor.Fm'

on:
  push:
    paths: 
      - episode.json
    branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Episode from YouTube To Anchor.Fm
        uses: Schrodinger-Hat/youtube-to-anchorfm@V1.0.3
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          EPISODE_PATH: /github/workspace
          POSTPROCESSOR_ARGS: \" --exec after_video:\"mv episode.mp3 tmp.mp3\" --exec after_video:\"ffmpeg -i tmp.mp3 -af silenceremove=stop_periods=-1:stop_duration=1:stop_threshold=-50dB episode.mp3
